# California state vehicle fleet

In [4]:
import pandas as pd
import geopandas as gpd
import matplotlib
import matplotlib.pyplot as plt
import geojson
import json
import jenkspy
import numpy as np
from pywaffle import Waffle
from altair import datum
import altair as alt
import altair_latimes as lat
alt.themes.register('latimes', lat.theme)
alt.themes.enable('latimes')
pd.options.display.max_columns = 50
pd.options.display.max_rows = 1000
pd.options.display.float_format = '{:,.2f}'.format
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [12]:
df = pd.read_csv('https://data.ca.gov/dataset/1b31c08e-b1a7-4459-8aef-41cfff61fc5e/resource/5c42e9f6-e172-4db4-9a51-ca1256b03a26/download/fleet-asset-management-system-open-data-2015-2019.csv', low_memory=False, encoding='Latin-1')

In [16]:
df.head()

,Agency,Report_Year,Disposed,Equipment_Number,Asset_Category,Model_Year,Make_Model,Postal_Code,Asset_Type,Weight_Class,Passenger_Vehicle,Payload_Rating,Shipping_Weight,Wheel_Type,Tire_Size,Fuel_Type,Engine_Configuration,Emissions_Type_Code,Primary_Application,Secondary_Application,Acquisition_Delivery_Date,SUV_Justification,Pickup_4_by_4_Justification,Acquisition_Method,Purchase_Price,Annual_Lease_Rate,Acquisition_Mileage,Disposition_Date,Transferred_To,Disposition_Method,Disposition_Reason,Disposition_Mileage,Disposition_Sold_Amount,Total_Miles
0,"African American Museum, California",2015,No,caam0103,Ground,2003,FORD ECONOLINE,90037,Van,Medium Duty,Yes,1,"5,147",Rear Wheel Drive,Null,Gasoline,Dedicated,Not Applicable,Mixed use,Not Applicable,10/7/2003,Not Applicable,Not Applicable,Purchase,"$13,000",Null,Null,Null,Not Applicable,Not Applicable,Not Applicable,Null,Null,Null
1,"African American Museum, California",2015,No,Null,No Data,Null,Not Applicable,90037,No Data,No Data,No,Null,Null,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,6/8/2003,Not Applicable,Not Applicable,Purchase,"$19,395",Null,Null,Null,Not Applicable,Not Applicable,Not Applicable,Null,Null,Null
2,"African American Museum, California",2016,No,caam0103,Ground,2003,FORD ECONOLINE,90037,Van,Medium Duty,Yes,1,"5,147",Rear Wheel Drive,Null,Gasoline,Dedicated,Not Applicable,Mixed use,Not Applicable,10/7/2003,Not Applicable,Not Applicable,Purchase,"$13,000",Null,Null,Null,Not Applicable,Not Applicable,Not Applicable,Null,Null,450
3,"African American Museum, California",2016,No,Null,No Data,Null,Not Applicable,90037,No Data,No Data,No,Null,Null,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,6/8/2003,Not Applicable,Not Applicable,Purchase,"$19,395",Null,Null,Null,Not Applicable,Not Applicable,Not Applicable,Null,Null,Null
4,"African American Museum, California",2017,No,caam0103,Ground,2003,FORD ECONOLINE,90037,Van,Medium Duty,Yes,1,"5,147",Rear Wheel Drive,Null,Gasoline,Dedicated,Not Applicable,Mixed use,Not Applicable,10/7/2003,Not Applicable,Not Applicable,Purchase,"$13,000",Null,Null,Null,Not Applicable,Not Applicable,Not Applicable,Null,Null,228

In [18]:
df[df['Report_Year'] == 2019].Fuel_Type.value_counts(normalize=True)

Gasoline                        0.42
85% Ethanol                     0.19
Diesel                          0.16
Not Applicable                  0.11
Electricity (battery powered)   0.10
LPG/Propane                     0.02
Compressed Natural Gas          0.00
Hydrogen                        0.00
85% Methanol                    0.00
Liquid Natural Gas              0.00
Biodiesel                       0.00
Renewable Diesel                0.00
Name: Fuel_Type, dtype: float64