# SSA Popular Baby Names

### Import Python tools and Jupyter configuration

In [1]:
%load_ext lab_black

In [2]:
import pandas as pd
import altair as alt
import altair_latimes as lat
import datetime as dt
import glob
import os

/Users/mhustiles/.local/share/virtualenvs/notebooks-xu8v5Vvv/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [3]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 1000
alt.data_transformers.disable_max_rows()
pd.options.display.max_colwidth = None

In [4]:
today = dt.datetime.today().strftime("%Y-%m-%d")

---

In [5]:
df = pd.read_csv("data/processed/names_births.csv", dtype={"year": str})

In [25]:
df[df["year"] == "2020"].sort_values("fprop", ascending=False)

,name,sex,count,year,male,female,total,prop,fprop,mprop
1733530,Olivia,F,17535,2020,1831432,1751046,3582478,0.004895,0.010014,NaN
1733531,Emma,F,15581,2020,1831432,1751046,3582478,0.004349,0.008898,NaN
1733532,Ava,F,13084,2020,1831432,1751046,3582478,0.003652,0.007472,NaN
1733533,Charlotte,F,13003,2020,1831432,1751046,3582478,0.003630,0.007426,NaN
1733534,Sophia,F,12976,2020,1831432,1751046,3582478,0.003622,0.007410,NaN
...,...,...,...,...,...,...,...,...,...,...
1764796,Zykell,M,5,2020,1831432,1751046,3582478,0.000001,NaN,0.000003
1764797,Zylus,M,5,2020,1831432,1751046,3582478,0.000001,NaN,0.000003
1764798,Zymari,M,5,2020,1831432,1751046,3582478,0.000001,NaN,0.000003
1764799,Zyn,M,5,2020,1831432,1751046,3582478,0.000001,NaN,0.000003
1764800,Zyran,M,5,2020,1831432,1751046,3582478,0.000001,NaN,0.000003

In [26]:
names = ["Eva", "Isabel", "Luna"]

In [27]:
name = df[(df["name"].isin(names)) & (df["sex"] == "F")].reset_index(drop=True)

In [29]:
line_chart = (
    alt.Chart(name)
    .mark_line(color="pink", size=4)
    .encode(
        x=alt.X(
            "year:T",
            title="Year",
            axis=alt.Axis(tickCount=5, grid=False),
        ),
        y=alt.Y(
            "fprop",
            title="Percentage of all names",
            stack=None,
            axis=alt.Axis(
                tickSize=0,
                domainOpacity=0,
                tickCount=6,
                offset=4,
                gridWidth=0.6,
                gridColor="#dddddd",
                format="%",
            ),
        ),
        color=alt.Color("name", title=" "),
    )
)


chart = (
    (line_chart)
    .properties(
        width=1000,
        height=600,
        title="Popularity of the name",
    )
    .configure_view(strokeOpacity=0)
    .configure_legend(orient="top", symbolType="stroke", labelFontSize=13)
    .configure_axis(labelFontSize=13)
    .configure_title(fontSize=20)
)

chart

alt.Chart(...)

In [31]:
chart.save("visuals/chart.png", scale_factor=2)